name: Makefile CI

on:
  push:
    tags:        
      - v*.**
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create download dir
      run: mkdir -p downloads

    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'OA-WCVP/ipni-oa'
        version: 'latest'
        file: "ipni-oa-data.zip"
        target: 'downloads/ipni-oa-data.zip'
        token: ${{ secrets.PAT }}

    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'OA-WCVP/catalog-number-access'
        version: 'latest'
        file: "catalog-number-access-data.zip"
        target: 'downloads/catalog-number-access-data.zip'
        token: ${{ secrets.PAT }}

    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'OA-WCVP/gbif-literature'
        version: 'latest'
        file: "gbif-literature-data.zip"
        target: 'downloads/gbif-literature-data.zip'
        token: ${{ secrets.PAT }}

    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'OA-WCVP/phytotaxa-oa'
        version: 'latest'
        file: "phytotaxa-oa-data.zip"
        target: 'downloads/phytotaxa-oa-data.zip'
        token: ${{ secrets.PAT }}

    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'OA-WCVP/wcvp-gbif-processing'
        version: 'latest'
        file: "wcvp-gbif-processing-data.zip"
        target: 'downloads/wcvp-gbif-processing-data.zip'
        token: ${{ secrets.PAT }}
        
    - name: Sanity check artifact download
      run: ls -ltra downloads

    - name: Installation 
      run: sudo apt-get update -y
      
    - name: Install texlive-latex-base texlive-latex-extra texlive-luatex texlive-science-doc texlive-science
      run: sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-luatex texlive-science-doc texlive-science
      
    - name: Install pandoc
      run: wget --quiet https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb; sudo dpkg -i pandoc-2.18-1-amd64.deb

    - name: Check pandoc version
      run: pandoc -v

    - name: Build all formats (PDF, docx and HTML)
      run: make all
      
    - uses: actions/upload-artifact@v3
      with:
        name: article.pdf
        path: build/article.pdf

    - uses: actions/upload-artifact@v3
      with:
        name: article.docx
        path: build/article.docx

    - uses: actions/upload-artifact@v3
      with:
        name: article.html
        path: build/article.html

    - name: Release with built documents
      uses: softprops/action-gh-release@v1
      with:
        files: build/article.docx
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    
      
